[blue_loadout]
  team_color_id = 23
  custom_color_id = 90
  car_id = 3031
  decal_id = 11594
  wheels_id = 11428
  boost_id = 6942
  antenna_id = 0
  hat_id = 0
  paint_finish_id = 4127
  custom_finish_id = 8783
  engine_audio_id = 4295
  trails_id = 5521
  goal_explosion_id = 6922
  [blue_loadout.paint]
    car_paint_id = 3
    decal_paint_id = 0
    wheels_paint_id = 3
    boost_paint_id = 4
    antenna_paint_id = 0
    hat_paint_id = 0
    trails_paint_id = 2
    goal_explosion_paint_id = 0

[orange_loadout]
  team_color_id = 34
  custom_color_id = 90
  car_id = 3031
  decal_id = 11594
  wheels_id = 11428
  boost_id = 6942
  antenna_id = 0
  hat_id = 0
  paint_finish_id = 4127
  custom_finish_id = 8783
  engine_audio_id = 4295
  trails_id = 5521
  goal_explosion_id = 6922
  [orange_loadout.paint]
    car_paint_id = 3
    decal_paint_id = 0
    wheels_paint_id = 3
    boost_paint_id = 14
    antenna_paint_id = 0
    hat_paint_id = 0
    trails_paint_id = 14
    goal_explosion_paint_id = 0
